language: node_js

node_js:
  - "10"

sudo: false
env:
  - TEST_SUITE=lint
  - TEST_SUITE=mocha

cache:
  directories:
    - node_modules

install:
  - npm ci

script:
  - if [ "$TEST_SUITE" == "lint" ]; then npm run lint; else npm run test; fi
