language: node_js

node_js:
  - "10"

sudo: false
env:
  - TEST_SUITE=lint
  - TEST_SUITE=data-schema

cache:
  directories:
    - node_modules

install:
  - npm ci

script:
    - if [ "$TEST_SUITE" == "lint" ]; then npm run lint; fi
    - if [ "$TEST_SUITE" == "data-schema" ]; then npm run test; fi
